[tool.poetry]
name = "alchemy"
version = "0.1.0"
description = ""
authors = ["bDrwx <a.bodosov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
